### ISSUE TITLE
The website is not reachable 

### ISSUE THREAD

**Issue by MarcSteven** [yulingtianxia/yulingtianxia.github.io#1]
Hi, Guys,
I found there is an error about your personal website - cannot visit, only show the info "it works!"

**Comment by MarcSteven** [comment]
It was weird, now it works, so closed it.

**Comment by MarcSteven** [comment]
@yulingtianxia  Hi, it has a relationship with the condition of the network.
1, VPN is closed and then visit the website 
<img width="1279" alt="Screen Shot 2020-11-07 at 15 22 42" src="https://user-images.githubusercontent.com/13824297/98434768-98655000-210d-11eb-9b47-8e5e1ede19dd.png">
2, Open  the VPN and then visit the website, it can be opened.
<img width="1280" alt="Screen Shot 2020-11-07 at 15 23 10" src="https://user-images.githubusercontent.com/13824297/98434781-b03cd400-210d-11eb-99c2-3c2c122f67fa.png">

**Comment by yulingtianxia** [comment]
I can't reappear this issue under 4G/Wifi network.

**Comment by MarcSteven** [comment]
It always appears when using the Wifi network. @yulingtianxia  But once opened the VPN, it worked well.

**Comment by yulingtianxia** [comment]
@MarcSteven I'm in a puzzle about the "It works!" page. I can't find this message in source code of my blog. May your network is attacked by session hijacking?

**Comment by MarcSteven** [comment]
@yulingtianxia  It has no relationship with session hijacking, I tried more times.
You can review the result from the pic as below:
<img width="1089" alt="Screen Shot 2020-11-09 at 18 57 07" src="https://user-images.githubusercontent.com/13824297/98533091-7dd1d900-22bd-11eb-9d14-8c9f90aba7f1.png">

**Comment by yulingtianxia** [comment]
@MarcSteven I'm using DNSPod and my blog is always down😢
<img width="791" alt="image" src="https://user-images.githubusercontent.com/433320/98546166-7e746a80-22d1-11eb-94d8-a7c0d8cefce4.png">

I don't know what the problem is, maybe DNS cache poisoning, or I should file my website with the Ministry of Industry and Information Technology🤷‍♀️

**Comment by MarcSteven** [comment]
@yulingtianxia It's weird, perhaps you need the second way to make it legal .
